### ISSUE TITLE
Allow waiting for multiple conditions

### ISSUE THREAD

**Issue by johanhaleby** [jayway/awaitility#24]
```
E.g.

await().until(repo::isNotEmpty, repo::hasAnyX);
```

Original issue reported on code.google.com by `johan.ha...@gmail.com` on 22 May 2014 at 11:54

**Comment by helsing** [comment]
It's not clear to me if the semantics of this method should be a logical AND or a logical OR? 
I suggest to skip this feature-request altogether, and let the client/user be explicit in their condition specification, e.g to use something similar to 

    await().until(allOf(repo::isNotEmpty, repo::hasAnyX)) - for logical AND

    await().until(anyOf(repo::isNotEmpty, repo::hasAnyX)) - for logical OR

**Comment by johanhaleby** [comment]
You're probably right. Thanks for your input, I'll close the issue.
