### ISSUE TITLE
Add between method as compliment to atMost

### ISSUE THREAD

**Issue by johanhaleby** [jayway/awaitility#38]
For example it would be cool to be able to do:

await().between(ONE_SECOND, FIVE_SECONDS).until(..)

Perhaps it's more clear to do:

await().atLeast(ONE_SECOND).and().atMost(FIVE_SECONDS).until(..)

**Comment by kelebra** [comment]
Hi, I would be more than glad to provide a pull request for this change.

Any thoughts on expected behavior in case condition is going to be executed before atLeast value?
Example: await().atLeast(ONE_SECOND).and().atMost(FIVE_SECONDS).until(..)
But result was obtained in 0.5 seconds. Should library throw an exception with message like "Not expected to finish earlier than 1 second"?

**Comment by johanhaleby** [comment]
I'm glad that you want to participate. I've thought about this a little bit but it might actually be quite a large change. I'm thinking that if we introduce this feature it would be good to unify this with the "atMost" concept. For example we may introduce something like a `WaitConstraint` which can either be an `AtMostWaitConstraint` (i.e. what is used when `atMost(..)` is used) or `IntervalWaitConstraint` that is used if we specify `between` or `atLeast` combined with `atMost`. Thus from the point of "awaitility core" it can just call the `WaitConstraint` instance (without knowing which one it is) to see if the condition is still valid from a timing perspective. What do you think?

**Comment by kelebra** [comment]
Sounds great and quite natural. I would like to try your idea one and provide pull request tomorrow :100:

**Comment by johanhaleby** [comment]
Sounds great!

lördag 19 mars 2016 skrev Oleksii <notifications@github.com>:

> Sounds great and quite natural. I would like to try your idea one and
> provide pull request tomorrow [image: :100:]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jayway/awaitility/issues/38#issuecomment-198616102>
>


-- 
Sent from my phone
