### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by PascalSchumacher** [jayway/awaitility#49]
What about a new release of awaitility?
 
The last release was half a year ago and I like to use the new groovy extension: https://github.com/jayway/awaitility/commit/1c1d0b28b16342353a4975b93dac48bdc9f02649

**Comment by johanhaleby** [comment]
I know its long overdue. I need to release another open source project of mine first (rest assured) but then I'll start working on a new release of awaitility. Next version will be 2.0 and package name will most likely be "org.awaitility".

**Comment by PascalSchumacher** [comment]
Thanks for releasing 2.0.0! :+1:

**Comment by johanhaleby** [comment]
Hope you like it :)
